apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: file-upload-hpa
  namespace: cloud-file-processor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: file-upload-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

